---
name: "КиноПоиск"
guid: "0c136f8a-ff77-4f2b-ade5-13462cae6216"
imageUrl: "https://kinopoisk.userecho.com/s/attachments/28876/0/1/25f8c0315e6ccb2aa6c2642e48f2c9e9.png"
version: "10.9.0.1"
targetAbi: "10.9.0"
framework: "net8.0"
owner: "svk"
overview: "Информация о фильмах и сериалах с КиноПоиска"
description: >
  Загружает рейтинг, описания, актёров, трейлеры и т.д. с сайта КиноПоиск.
  Может потребоваться зарегистрировать свой ApiToken, см. информацию в параметрах плагина.
  Для точного распознавания рекомендуется указывать id фильма с сайта КиноПоиск в имени файла в формате kp-12345 или kp12345.
  Подробнее см. https://github.com/LinFor/jellyfin-plugin-kinopoisk/blob/master/README.md
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.Kinopoisk.dll"
- "KinopoiskUnofficialInfo.ApiClient.dll"
changelog: >
  Fix bugs
